spring:
  application:
    name: kafka-producer-service
  kafka:
     producer:
        bootstrap-servers: localhost:29092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        acks: all

logging:
  level:
    root: INFO
server:
  port: 8021
kafka.topic.name: sample.producer.topic